8786 inheritance
MistaTwista/MovieParser pull request #1
Opened 2017-09-12 15:51 UTC by MistaTwista

feat: tests moved to RSpec
feat: Movie subclasses added
feat: Cinema implemented
feat: Cinemas sublcasses added

2017-09-13 08:21 UTC, zverok requested changes
Это ещё не всё, но давай кусками исправлять. :)

2017-09-13 08:21 UTC, zverok commented on Gemfile
> +git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }
Это тебе не надо :)

2017-09-13 08:21 UTC, zverok commented on lib/cinemas/cinema.rb
> +    "#{format_time(movie_start)} - #{format_time(movie_end)}"
По-моему, префикс в названии метода `movie_` должен подсказать, что это можно сделать методом класса `Movie` ;)

2017-09-13 08:21 UTC, zverok commented on lib/cinemas/netflix.rb
> +    raise "Insufficient funds" if @account < amount
Лучше в текстах ошибок оставлять контекст (сколько сейчас на счету, сколько надо)

2017-09-13 08:21 UTC, zverok commented on lib/cinemas/netflix.rb
> +  end
По-моему это хочет быть константой. Может быть даже константой в классах фильмов ;)

2017-09-13 08:21 UTC, zverok commented on lib/cinemas/theatre.rb
> +  end
По-моему эти три метода очень неэкономны (если логика кинотеатра поменяется — задолбаешься методы менять). Хорошо бы их вынести в константу или пару констант максимум, мне так кажется.

2017-09-13 08:21 UTC, zverok commented on lib/movie.rb
> +    "#{title} (#{actors}) #{year}; #{genre}; #{length} min"
Почему? Было красивше. Да и кстати 2 дополнительных переменные тебе не нужны, можно прям в строке это всё собрать, мне кажется. (Использовать метод `#format` если строка становится слишком жырной)

2017-09-13 08:21 UTC, zverok commented on lib/movie.rb
> +      .downcase.split('_').first.to_sym
Да ладно? `self.class.name.scan(/(\w+)Movie/).first.downcase` не? И сделать это методом класса, чтобы было так:
```ruby
def period
  self.class.period
end
```

2017-09-13 08:21 UTC, zverok commented on lib/movies/new_movie.rb
> +  end
Это перебор с выносом всяких вещей в атомарные методы :)

2017-09-13 08:21 UTC, zverok commented on spec/movies_mock.rb
> +end
Идея понята, а воплощение слишком замороченное. Лучше использовать `shared_context` и `let`

2017-09-13 08:21 UTC, zverok commented on spec/movie_builder_spec.rb
> +      end
Здесь бы `subject` использовать, получилось бы короче и читабельнее:
```ruby
subject { builder.class }
context 'when AncientMovie' do
  ...
  it { is_expected.to eq AncientMovie }
end

2017-09-13 08:21 UTC, zverok commented on spec/movie_builder_spec.rb
> +      let(:mock) { MoviesMock::ANCIENT_MOVIE }
Я думаю этот let лучше называть не по содержимому, а по применению. То есть скажем `movie_data`

2017-09-13 08:21 UTC, zverok commented on spec/cinemas/netflix_spec.rb
> +        .to output(/Dark Knight/).to_stdout
На самом деле подход правильный, только теперь бы ещё отдельно `select_from_collection` протестировать (что он выбирает правильный фильм)  — а потом, как здесь, с застабленным select протестировать что происходит при `show`.

2017-09-13 08:21 UTC, zverok commented on spec/cinemas/netflix_spec.rb
> +        .to output(/Dark Knight/).to_stdout
Кстати, забыл протестировать что деньги снялись со счёта ;)

2017-09-13 08:29 UTC, MistaTwista commented on lib/cinemas/netflix.rb
> +  end
Но цена от кинотеатра к кинотеатру может меняться. Например, я не знаю на текущий момент будет ли где-то еще использоваться цена или нет. Будет она фиксирована в фильме или о цене будет знать конкретный кинотеатр.

2017-09-13 08:30 UTC, MistaTwista commented on lib/cinemas/theatre.rb
> +  end
Мне они самому не нравятся)

2017-09-13 08:31 UTC, MistaTwista commented on lib/movie.rb
> +    "#{title} (#{actors}) #{year}; #{genre}; #{length} min"
Длина строки и читалось хуже, подумаю

2017-09-13 08:32 UTC, MistaTwista commented on lib/movie.rb
> +      .downcase.split('_').first.to_sym
На счет метода класса не уверен, в остальном согласен)

2017-09-13 08:34 UTC, zverok commented on lib/movie.rb
> +    "#{title} (#{actors}) #{year}; #{genre}; #{length} min"
```ruby
format('%s (%s) %i; %s - %i min',
  title,
  actors.join(', '),
  year,
  genre.join(', '),
  length  
)

2017-09-13 08:35 UTC, MistaTwista commented on spec/cinemas/netflix_spec.rb
> +        .to output(/Dark Knight/).to_stdout
Ой, точно помню писал где-то этот тест, видимо в процессе куда то убил :)

2017-09-13 08:35 UTC, zverok commented on lib/movie.rb
> +      .downcase.split('_').first.to_sym
дык а чо не уверен-то? в принципе логика же простая — то что не использует переменных объекта, и не должно являться методом объекта (иногда мы её нарушаем, просто для простоты, но в целом так). У всего класса этот период один и тот же, так что ....

2017-09-13 08:40 UTC, MistaTwista commented on lib/movies/new_movie.rb
> +  end
Я это больше для стаба сделал :)

2017-09-13 08:42 UTC, zverok commented on lib/movies/new_movie.rb
> +  end
Да, я понял. Но это делается не так, если уж очень хочется текущий год застабать. Можно `allow(Time).to receive(:now)`, а можно как нормальный человек timecop подключить

2017-09-13 08:44 UTC, zverok commented on lib/cinemas/theatre.rb
> +  end
Экспериментируй! Они все должны использовать одни и те же _данные_, хранимые предположительно в константах.

2017-09-15 09:00 UTC, zverok reviewed
Пока так.

2017-09-15 09:00 UTC, zverok commented on lib/cinemas/netflix.rb
> +    end
Этот код хочет константу-хеш ;)

2017-09-15 09:00 UTC, zverok commented on lib/cinemas/theatre.rb
> +    0..6 => EVENING
Хорошо бы ночью перерыв сделать в работе (это поднимет несколько мелких вопросов по обработке этого дела в коде). И ещё, мне кажется что 7...13 (с excluding end) будет точнее отражать происходящее. А так получается «с 7 до 12 показываем то-то, с 13 до 17 — то-то, а с 12 до 13 иди гуляй»

2017-09-15 09:00 UTC, zverok commented on lib/cinemas/theatre.rb
> +  MORNING = { time: :morning, filter: [:period, :ancient] }
а) может фильтр хешом-то?
б) может это всё должен быть один хеш (названия периодов — ключи, фильтры — значения), а?

2017-09-15 09:00 UTC, zverok commented on lib/cinemas/theatre.rb
> +    end
А чего ж each-то? У тебя же теоретически сейчас может быть только один период, не?

2017-09-15 09:00 UTC, zverok commented on lib/movie.rb
> +  def match?(options)
Я бы назвал параметр filters, не?

2017-09-15 09:00 UTC, zverok commented on lib/movie.rb
> +  def match?(options)
И вообще это довольно странный метод. Мы же вроде воплощали уже фильтрацию, и довольно мощную?..

2017-09-15 09:00 UTC, zverok commented on spec/movies/new_movie_spec.rb
> +  it_behaves_like 'a movie'
На самом деле, это не вполне обязательно — он же унаследован от Movie, достаточно «общее» поведение в тестах Movie протестировать.

2017-09-15 09:00 UTC, zverok commented on spec/support/shared_context.rb
> +end
А в чём ценность этого shared context?

2017-09-15 09:00 UTC, zverok commented on spec/movie_collection_spec.rb
> +    end
Хорошо бы тест на то что будет если поле незнакомое.

2017-09-15 09:00 UTC, zverok commented on spec/movie_collection_spec.rb
> +      expect(collection.filter(director: 'Nolan').count).to eq 7
Мне кажется, что тесты по количеству слабоваты. Я бы сказал `.to all have_attributes(director: ....)`

2017-09-15 09:10 UTC, MistaTwista commented on lib/movie.rb
> +  def match?(options)
оно было в коллекции, а узнать про сам фильм негде :) это можно сделать и в тесте, но тут смотрится логично и бесплатно получаем еще функционал

2017-09-15 09:12 UTC, MistaTwista commented on lib/cinemas/theatre.rb
> +    0..6 => EVENING
а там технологический перерыв ;)

2017-09-15 09:14 UTC, MistaTwista commented on lib/cinemas/theatre.rb
> +  MORNING = { time: :morning, filter: [:period, :ancient] }
с фильтром хешом на мой взгляд менее удобно работать, массив точно знаем - 0 ключ, 1 значение, можно конечно :symbol.to_a, но зачем? А с хешем нужно спрашивать ключи, потом ходить собирать значения.

2017-09-15 09:23 UTC, zverok commented on lib/cinemas/theatre.rb
> +  MORNING = { time: :morning, filter: [:period, :ancient] }
Почему? Мы можем сделать `hash.each` чтобы обойти и ключи и значения. А в качестве константы оно выглядит куда читабельнее.

2017-09-15 09:26 UTC, zverok commented on lib/movie.rb
> +  def match?(options)
Так перенеси реализацию из коллекции в фильм, будет лучше. А так у тебя дублируется функционал же, с небольшими отличиями.

2017-09-15 09:38 UTC, MistaTwista commented on lib/cinemas/theatre.rb
> +  MORNING = { time: :morning, filter: [:period, :ancient] }
Но у нас то тут не предполагается что-то обходить? У нас 1 значение для фильтра, их не будет 2, по крайней мере пока нигде не пишут об этом :)

2017-09-15 13:23 UTC, zverok commented on lib/cinemas/theatre.rb
> +  MORNING = { time: :morning, filter: [:period, :ancient] }
Да ладно, вот это уже сознательная пессимизация требований. Очевидно же, что предполагается что все фильтры, какие фильм понимает, могут быть указаны в расписании (типа «у нас сегодня ночь старых американских комедий»)

2017-09-16 11:20 UTC, MistaTwista commented on lib/cinemas/theatre.rb
> +  MORNING = { time: :morning, filter: [:period, :ancient] }
ну тогда стоит сделать там не просто хеш, а массив? Чтоб можно было несколько выборок делать

2017-09-17 07:41 UTC, zverok commented on lib/cinemas/theatre.rb
> +  MORNING = { time: :morning, filter: [:period, :ancient] }
Моя интуция говорит, что по крайней мере самая читабельная константа выглядит как-то так:
```ruby
{
  morning: {period: 'Classic', genre: 'Comedy'},
  day: {genre: %w[Action Comedy Drama], year: 2010..Date.today.year},
  evening: {genre: 'Horror'}
}
```
м?

2017-09-18 06:24 UTC, zverok requested changes

2017-09-18 06:24 UTC, zverok commented on lib/cinemas/netflix.rb
> +    raise NothingToShow unless movie
(это из мелочей) контекст бы ошибке (типа не найдено по таким-то фильтрам; и кстати параметр лучше бы назвать «filters», options — нам ничего не говорит.

2017-09-18 06:24 UTC, zverok commented on lib/cinemas/netflix.rb
> +    @movie = select_from_collection filter(options)
зачем в instance variable?

2017-09-18 06:24 UTC, zverok commented on lib/cinemas/cinema.rb
> +  def select_from_collection(collection)
Кстати, я бы сказал что название этого метода скорее должно быть какое-то типа `peek_random`. Потому что а) `select` подразумевает несколько разных; б) `from_collection` совершенно бессмысленная добавка (ещё и ложная — как будто он «из всей коллекции» выбирает, а не из переданного массива); в) собственно суть (что фильм выбирается полу-случайный) в названии не видна

2017-09-18 06:24 UTC, zverok commented on lib/cinemas/theatre.rb
> +    PERIODS[period].map { |param, value| filter(param => value) }.flatten
`filter(PERIODS[period])`, не?..

2017-09-18 06:24 UTC, zverok commented on lib/cinemas/theatre.rb
> +    }.compact
`map` + `if` называется `select` ;)

2017-09-18 06:24 UTC, zverok commented on lib/movie.rb
> +  end
Я бы сказал что время начала лучше параметром передавать, тогда этот метод будет полезнее (например, нарисовать какое-нибудь там расписание фильмов идущих друг за другом)

2017-09-18 06:24 UTC, zverok commented on lib/movie.rb
> +    param, matcher = filter
`def matches?(field, filter_value)` разумнее. И в `matches_all?` → `filters.all? { |name, value| matches?(name, value) }`

2017-09-18 06:24 UTC, zverok commented on spec/cinemas/netflix_spec.rb
> +      netflix.pay(10)
Это бы в `before`

2017-09-18 06:24 UTC, zverok commented on spec/cinemas/netflix_spec.rb
> +    end
Если объединить с предыдущим примером (через `.and`) не придётся подавлять вывод насильно.

2017-09-18 06:24 UTC, zverok commented on spec/cinemas/netflix_spec.rb
> +        .to change{netflix.account}.from(10).to(7)
Лучше `change(netflix, :account)` (в выводе упавшего матчера лучше будет смотреться, и в `rspec --format doc`

2017-09-18 06:24 UTC, zverok commented on spec/cinemas/theatre_spec.rb
> +      end
Можно `filter` и `time` как параметры передать, будет вот так:
```ruby
it_behaves_like 'choose movie by time', '14:05, genre: ['Comedy', 'Adventure']
```
аккуратнее, не?

2017-09-18 06:24 UTC, zverok commented on spec/errors_spec.rb
> +end
0_0 серьёзно? Что тестируем?

2017-09-18 06:24 UTC, zverok commented on spec/movies/ancient_movie_spec.rb
> +    it { expect(movie.to_s).to eq 'Casablanca - ancient movie (1942)' }
К слову, с гемом rspec-its, и если определить `movie` как `subject` для тестов (что в любом случае стоило бы сделать, зря ты `subject`-ами не пользуешься), тут можно написать `its(:to_s) { is_expected.to eq .... }`

2017-09-18 06:24 UTC, zverok commented on spec/movies/classic_movie_spec.rb
> +        .to receive(:other_directors_movies).and_return('Some, Other, Movies')
А вот так не стоило бы делать — тут ты полностью полагаешься на «скрытое» поведение класса. Я бы ему передал стаб коллекции, и на этом стабе бы сказал что `allow to receive(:filter).and return`... — тогда ты пользуешься только публичными методами в тесте, и показываешь что собственно произойдёт (откуда кино возьмёт другие фильмы)

2017-09-18 06:24 UTC, zverok commented on spec/support/matches_all.rb
> +end
Кстати, немношк уродливо, но вместо кастомного матчера можно так: `expect(something).to be_matches_all(filter)` (`be_<something>` автоматически транслируется в вызов `<something>?` и проверку результата)

2017-09-18 06:24 UTC, zverok commented on spec/support/random_movie_chooser.rb
> +    end
Я бы сказал про это всё в целом (учитывая вчерашние разговоры):
1. тестируем, что фильмы фильтруются нужными фильтрами
2. тестируем, что именно отфильтрованное выводится

т.е.
1. `expect(theatre).to receive(:filter).with(filter).and_return([one_test_movie])` (`filter` протестировать отдельно)
2. `expect(theatre.show(ftime)).to ouput("как должен вывестись one_test_movie")`

и всё. две строчки, и всё протестировано корректно :)

2017-09-19 20:14 UTC, MistaTwista commented on lib/cinemas/theatre.rb
> +    }.compact
это да, но у меня при select будет не то, что я хочу
```
expected: [{"Alien"=>[:evening]}]
got: [{"Alien"=>[[17..23, :evening]]}]
```

2017-09-20 04:04 UTC, zverok commented on lib/cinemas/theatre.rb
> +    }.compact
ну `select` + `map`, чо. `map` + `compact` очень плохо читается (намерения не видны).

2017-09-20 08:08 UTC, zverok requested changes

2017-09-20 08:08 UTC, zverok commented on lib/cinemas/theatre.rb
> +    result << :never if result.empty?
Такой трюк, мне кажется, лишний. Вызывающий код сам поймёт что «никогда не показывают», если там пустота (и, в зависимости от своих целей, например сделать `....reject { |name, period| period.empty? }`

2017-09-20 08:08 UTC, zverok commented on lib/cinemas/theatre.rb
> +    movies.map { |m| { m.title => when_to_show_movie(m) } } if movies.any?
Кстати¹, этот `if` не нужен, мне кажется.
Кстати², хорошо бы вернуть всё же один хеш, а не массив хешей.

2017-09-20 08:08 UTC, zverok commented on lib/cinemas/theatre.rb
> +    }.compact
Так чего, обновишь?

2017-09-20 08:08 UTC, zverok commented on spec/cinemas/cinema_spec.rb
> +  let(:movie_builder) { MovieBuilder.build_movie(ancient_movie) }
это же не `movie_builder`, а `ancient_movie`, зачем ты читателя обманываешь?.. код дальше тяжело читать.

2017-09-20 08:08 UTC, zverok commented on spec/cinemas/cinema_spec.rb
> +  end
А что именно ты тестируешь в этом блоке? Поведение какого метода?

2017-09-20 08:08 UTC, zverok commented on spec/cinemas/netflix_spec.rb
> +          .to raise_error(RuntimeError, /Insufficient funds/)
5.times — лишнюю вещь читать и обдумывать. Стоит сделать по-другому (например, вынести `initial_money` в `let` и здесь его сделать равным другому значению)

2017-09-20 08:08 UTC, zverok commented on spec/cinemas/netflix_spec.rb
> +        .and_return(movie_builder)
Из этих двух примеров стоит вынести «что есть показывать» в let, и «какие фильмы у нас есть» — в before. Будет читабельнее.

2017-09-20 08:08 UTC, zverok commented on spec/factories/movie_factory.rb
> +end
Зачем?

2017-09-20 09:36 UTC, MistaTwista commented on spec/factories/movie_factory.rb
> +end
Зачем вообще всё или что-то конкретное? :) ну удобно же иногда взять и построить нужное без необходимости готовить файлы, парсить и т.п. можно было конечно использовать просто OpenStruct в месте где оно надо и не тянуть ActiveSupport вместе с FactoryGirl, но я подумал, что дальше оно может пригодиться :)

2017-09-20 13:13 UTC, zverok approved these changes
Поехали дальше :) Но комменты внимательно почитай!

2017-09-20 13:13 UTC, zverok commented on lib/cinemas/netflix.rb
> +    movies.map { |m| { m.title => PRICE_LIST[m.period] } } if movies.any?
И тоже, кстати — почему массив хешей, что это за формат такой дикий?

2017-09-20 13:13 UTC, zverok commented on lib/cinemas/netflix.rb
> +  end
Это кстати немножко перебор абстракций, с этим методом :) Хотя так иногда делают, но скорее в такой форме:
```ruby
def validate_enough!(amount)
  raise "Insufficient funds. Cost #{amount} and you have #{account}" if account < amount
end

# чтобы потом:
validate_enough!(amount)
@account -= amount
```
(менять ничего не надо, просто так, для общего образования)

2017-09-20 13:13 UTC, zverok commented on lib/cinemas/theatre.rb
> +    end
```ruby
filter(title: title).map { |m| [m.title, when_to_show(m)] }.to_h
```
не?

2017-09-20 13:13 UTC, zverok commented on spec/cinemas/cinema_spec.rb
> +  end
Смотри:
```ruby
before { allow(cinema).to receive(:movies).and_return(movies) }
subject { cinema.show }
context 'when nothing to show' do
  let(:movies) { [] }
  it { expect { subject }.to raise_error NothingToShow }
end

context 'when exactly one movie' do
  let(:movies) { [current_movie] }
  before { Timecop.freeze(Time.parse('18:15')) }
  it { expect { subject }.to ... }
end
```

Чувствуешь разницу? Каждый `it` подчёркивает, что именно он тестирует. Каждый контекст последовательно описывает контекст этого тестирования. Думать не надо!

2017-09-20 13:51 UTC, MistaTwista commented on lib/cinemas/netflix.rb
> +    movies.map { |m| { m.title => PRICE_LIST[m.period] } } if movies.any?
:trollface: но оно не специально, конечно, просто нигде не описано и как использовать будет тоже не ясно, вот я видимо и оставил без внимания формат, а так то да, странненько))

2017-09-20 18:32 UTC, merged